# Generated by Django 5.2 on 2025-04-17 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0018_alter_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='exec_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishkart.restaurant'),
        ),
    ]
