# Generated by Django 5.2 on 2025-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0019_remove_orders_exec_id_remove_orders_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='veg',
        ),
        migrations.AddField(
            model_name='orders',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='main_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
