# Generated by Django 5.2 on 2025-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0020_remove_menu_veg_orders_featured_orders_main_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay')], max_length=20),
        ),
    ]
