# Generated by Django 5.2 on 2025-04-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0021_alter_orders_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.PositiveIntegerField(choices=[(1000, '1 kg'), (250, '250 grams'), (500, '500 grams'), (750, '750 grams')], default=1000),
        ),
    ]
