# Generated by Django 5.2 on 2025-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0022_menu_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='main_product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='sold_out',
        ),
        migrations.AddField(
            model_name='menu',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='main_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
