# Generated by Django 5.2 on 2025-04-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0023_remove_orders_featured_remove_orders_main_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryexec',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='Building',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='Floor',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='addresses',
            field=models.CharField(default=False, max_length=2000),
        ),
        migrations.DeleteModel(
            name='addresses',
        ),
        migrations.DeleteModel(
            name='DeliveryExec',
        ),
    ]
