# Generated by Django 5.2 on 2025-04-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0024_remove_deliveryexec_user_remove_restaurant_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_delivery',
        ),
    ]
