# Generated by Django 5.2 on 2025-04-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0025_remove_user_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
