# Generated by Django 5.2 on 2025-04-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishkart', '0029_orders_created_at_orders_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Fishlist',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='menu_item',
            new_name='fish_item',
        ),
        migrations.RenameField(
            model_name='fishlist',
            old_name='food_image',
            new_name='fish_image',
        ),
        migrations.RenameField(
            model_name='fishlist',
            old_name='food_name',
            new_name='fish_name',
        ),
    ]
